version: '3'
services:
  mautic:
    image: mautic/mautic:latest
    links:
      - mauticdb:mysql
    ports:
      - 8080:80
    depends_on:
      - mauticdb
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
    volumes:
      - './:/var/www/html'

  mauticdb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
    ports:
      - 3306:3306
