version: '3'
services:
  mautic:
    image: quay.io/medullanmps/vara-mautic:v2.15.2-v2.2.0
    links:
      - mauticdb:mysql
    ports:
      - 8080:80
    depends_on:
      - mauticdb
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
      # manually control campaign execution for testing
      # - CAMPAIGN_EXECUTION_INTERVAL=0 0 * * *
    volumes:
      - './:/var/www/html:delegated'

  mauticdb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
    ports:
      - 3306:3306
